### ISSUE TITLE
Doubts about function

### ISSUE THREAD

**Issue by guleng** [sighupio/permission-manager#14] opened 2020-03-06 12:39 UTC
<h1>First of all, thanks to the producers. This tool is what we need most now</h1>

![image](https://user-images.githubusercontent.com/40238640/76084242-6635a880-5fea-11ea-9cc7-48426e2e33a4.png)

I don't know what this function is, I don't understand

##

![image](https://user-images.githubusercontent.com/40238640/76084583-258a5f00-5feb-11ea-8ce6-88f8e3240b2b.png)
This copy button doesn't work in my Chrome browser

**Comment by ralgozino** [comment] 2020-03-06 21:19
Hi @guleng ! Thanks for reaching out!

For your first question, what that combobox does is enabling (or not) access to resources that are cluster scoped and do not belong to a namespace, for example, listing all the namespaces of the cluster.

You can see the actual permissions here:
- Read-Only: https://github.com/sighupio/permission-manager/blob/master/k8s/k8s-seeds/seed.yml#L67
- Admin: https://github.com/sighupio/permission-manager/blob/master/k8s/k8s-seeds/seed.yml#L99

We should improve the docs with this information.

On the other hand, for the copy button problem, could you please open the development console of your browser and tell us if you see any error message? also, are you testing with the Docker image from our registry or are you building the one from the source? I can't reproduce the problem with latest chrome on macOS Catalina at least.

**Comment by guleng** [comment] 2020-03-07 11:49
@ralgozino    My browser is chrome (80.0.3987.122) and macOS Catalina, but there are such errors.
![image](https://user-images.githubusercontent.com/40238640/76142829-3e0e7e00-60ac-11ea-8251-a1f8f722b080.png)

My image is: quay.io/sighup/permission-manager:1.5.0

**Comment by guleng** [comment] 2020-03-13 00:21
@ralgozino ？

**Comment by ralgozino** [comment] 2020-03-13 12:54
hi @guleng , I'm sorry I can't reproduce none of the issues that you are having.

I've even tried to delete the app and re-deployed it and the users are still there. They're saved as a Kubernetes resources so it very weird that they get deleted by deleting the pod. 

Are you using some kind of browser extension that could be interfiering with the app? 
Could please try a fresh install following the installation docs?
https://github.com/sighupio/permission-manager/blob/master/docs/installation.md

**Comment by iknite** [comment] 2020-04-13 15:50
Hi @guleng, 

I've been testing some possible scenarios about the users lost that you mentioned before. Deleting just the pod did not delete the user created. (but if you delete the `k8s/seed` folder will do. 
[](url)
```
$ k delete -f k8s/deploy.yaml
deployment.apps "permission-manager-deployment" deleted 
service "permission-manager-service" deleted    

$ k get permissionmanagerusers
NAME                             AGE
permissionmanager.user.b-test   12m                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 

$ k apply -f k8s/deploy.yaml   
deployment.apps/permission-manager-deployment created
service/permission-manager-service created   
```
Also I was unable to reproduce the copy bug. I'm not sure how to help further. 
![imagen](https://user-images.githubusercontent.com/745710/79135013-fc5dab00-7dae-11ea-916a-e31dfd308b9b.png)

I'm closing the issue, but if you're able to give us more context, please continue it and we will try our best.

**Closed by iknite** 2020-04-13 15:50 UTC
Labels: bug, good first issue
